name: LHeads
version: '1.0'
main: net.crsimple.lightHeads.LHeads
api-version: '1.20'
authors: [ CrSimple_ ]
description: Lightweight heads essentials plugin

commands:
  lheads:
    usage: /heads <give|random> <args>
    aliases:
      - heads
